# DO NOT EDIT THIS FILE -- HWasly auto-generated file
{% if helpers.exists('HWasly.relayd.general.enabled') and HWasly.relayd.general.enabled|default("0") == "1" %}
osrelayd_enable="YES"
{% else %}
osrelayd_enable="NO"
{% endif %}
