PLUGIN_NAME=		etpro-telemetry
PLUGIN_VERSION=		1.6
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		ET Pro Telemetry Edition
PLUGIN_MAINTAINER=	ad@hwasly.org
PLUGIN_WWW=		https://docs.hwasly.org/manual/etpro_telemetry.html

.include "../../Mk/plugins.mk"
